[package]

name = "cssparser"
version = "0.1.0"
authors = [ "Simon Sapin <simon.sapin@exyr.org>" ]

[[lib]]

name = "cssparser"
path = "lib.rs"

[dependencies.encoding]

git = "https://github.com/lifthrasiir/rust-encoding"
