[package]

name = "cssparser"
version = "0.3.2"
authors = [ "Simon Sapin <simon.sapin@exyr.org>" ]

description = "Rust implementation of CSS Syntax Level 3"
documentation = "http://servo.github.io/rust-cssparser/cssparser/index.html"
repository = "https://github.com/servo/rust-cssparser"
readme = "README.md"
keywords = ["css", "syntax", "parser"]
license = "MPL-2.0"


[dev-dependencies]
rustc-serialize = "0.3"
tempdir = "0.3"


[dependencies]
encoding = "0.2"
matches = "0.1"
