[package]

name = "cssparser"
version = "0.5.3"
authors = [ "Simon Sapin <simon.sapin@exyr.org>" ]

description = "Rust implementation of CSS Syntax Level 3"
documentation = "http://servo.github.io/rust-cssparser/cssparser/index.html"
repository = "https://github.com/servo/rust-cssparser"
readme = "README.md"
keywords = ["css", "syntax", "parser"]
license = "MPL-2.0"


[dev-dependencies]
rustc-serialize = "0.3"
tempdir = "0.3"

[dependencies.serde]
version = "0.6.6"
optional = true

[dependencies.serde_macros]
version = "0.6.5"
optional = true

[dependencies.heapsize]
version = ">=0.1.1, <0.4.0"
optional = true

[dependencies.heapsize_plugin]
version = "0.1.0"
optional = true

[dependencies]
encoding = "0.2"
matches = "0.1"

[features]
serde-serialization = [ "serde", "serde_macros" ]
heap_size = [ "heapsize", "heapsize_plugin" ]
